name: Daily Stock Data ETL

# Jadwal di jalankan 
 # Jalan setiap hari Senin - Jumat jam 09:00 UTC (sama dengan 16:00 WIB)
on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch: 

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest 

    steps:
      # 1. Mengambil Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up python on server 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install library dari requirements.txt
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4. RUN SCRIPT PYTHON 
      - name: Run ETL Script
        run: python etl_stock.py

      # 5. Simpan (Commit) database SQLite yang baru di-update kembali ke GitHub
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add market_data.db
          git commit -m "Automated ETL: Update stock database" || exit 0
          git push
